### ISSUE TITLE
Webpack error when using v5.0.0

### ISSUE THREAD

**Issue by bernier** [AnomalyInnovations/serverless-bundle#259]
`WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
   - configuration.module.rules[1].resolve has an unknown property 'fullySpecified'. These properties are valid:
     object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, ignoreRootsErrors?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, preferAbsolute?, resolver?, roots?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }`
     
 serverless offline won't start because of this error

**Comment by bernier** [comment]
@jayair no, still the same issue after upgrading to 5.0.2

`Serverless: Bundling with Webpack...
 
 Webpack Options Validation Error ------------------------
 
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
   - configuration.module.rules[1].resolve has an unknown property 'fullySpecified'. These properties are valid:
     object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, ignoreRootsErrors?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, preferAbsolute?, resolver?, roots?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
     -> Options for the resolver
      at webpack (/Users/alex/Projects/serverless-project/node_modules/webpack/lib/webpack.js:31:9)`

**Comment by bernier** [comment]
@jayair not sure if it helps

```
 Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              16.13.0
     Framework Version:         2.64.1 (local)
     Plugin Version:            5.5.0
     SDK Version:               4.3.0
     Components Version:        3.17.1
   ```

**Comment by rodrigogs** [comment]
Same here

**Comment by ghostnumber7** [comment]
This issue is not related the the one fixed in 5.0.2. I think the solution for this case is to use [enforceExtension](https://webpack.js.org/configuration/resolve/#resolveenforceextension)  instead of using `fullySpecified` [here](https://github.com/AnomalyInnovations/serverless-bundle/blob/3e59331faac6e7af8b095ed8a8ac3db082a42785/src/webpack.config.js#L200)

**Comment by jayair** [comment]
@ghostnumber7 Oh I see. Feel free to submit a PR with a test case and I'll merge it. Thanks!

**Comment by ghostnumber7** [comment]
After some more digging, it seams that `fullySpecified` was added [here](https://github.com/webpack/webpack/commit/205bbb4c0d181c6770108c3d8b5e1818867776e3) on July 17 (and can't see exactly which version does have it for the first time). Maybe updating webpack version would do the trick (was wrong in the previous comment). Configuration does exist, so only thing I can think of is having an old version of webpack that matches the version we specify but does not have that property

**Comment by bernier** [comment]
Any news? Don't mean to be pushy but this issue has been opened in August and hasn't been resolved. The issue is still happening with the latest version 5.2.0. Thanks

**Comment by jayair** [comment]
I haven't had a chance to dig into this. Feel free to open a PR with a fix and I'll take a look right away.

**Comment by rodrigogs** [comment]
I totally gave up on updating this library. It does not work properly since 5.0.

**Comment by bernier** [comment]
I started a new project and started digging a little more through my base files.

I might have been resolved this issue by doing:

```
npm list webpack
npm remove cache-loader
```

Basically, npm list webpack will list the versions of webpack used by the project.
Another version of webpack was installed for cache-loader and was probably conflicting with the one used by serverless-bundle

I'm now able to use serverless-bundle 5.3.0

**Comment by yspreen** [comment]
hey, so, just found this project. seems like it's currently broken? nobody answered [this](https://stackoverflow.com/questions/69490812/error-on-fullyspecified-of-webpack-config-js-but-no-config-exists) so question either...

I'll just downgrade to 4.x I guess. It's a shame that this simple webpack flag seems to be impossible to add.

**Comment by jayair** [comment]
Please feel free to open a PR!

**Comment by yspreen** [comment]
In the docs you specifically say that you believe all webpack configs are covered and if anything's missing just to create a github issue 😅 

this has been open for 7 months now. I agree, I should just open the PR myself, but I sadly don't have the time. will have to stick to 4.x for now :(

**Comment by yspreen** [comment]
@jayair if I were to create a PR it would be for the missing functionality to override forceExclude. bc some layers (see https://github.com/fusebit/everynode/issues/3 ) don't have the SDK included

**Comment by jayair** [comment]
Yeah if the PR describes what the fix is and has some tests that would be great.

**Comment by bernier** [comment]
@jayair @yspreen please refer to the solution I used to fix the issue on my end. You might be able to do something similar. If not feel free to open a PR  https://github.com/AnomalyInnovations/serverless-bundle/issues/259#issuecomment-1043621908
